INFO| "test_run" выполнен успешно
WARNING| Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "/Users/gospoza/PycharmProjects/homework5/Git/домашка/tests_12_4.py", line 32, in test_run
    runner2 = runner.Runner("Бегун 2", speed='df')
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Runner.__init__() got an unexpected keyword argument 'speed'
INFO| "test_walk" выполнен успешно
WARNING| Неверная скорость для Runner
Traceback (most recent call last):
  File "/Users/gospoza/PycharmProjects/homework5/Git/домашка/tests_12_4.py", line 19, in test_walk
    runner1 = runner.Runner("Бегун 1", speed=-10)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Runner.__init__() got an unexpected keyword argument 'speed'
